# Generated by Django 4.2.3 on 2024-12-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='submited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='submited_status',
            field=models.CharField(blank=True, choices=[('OnTime', 'On Time'), ('late', 'Late')], max_length=20, null=True),
        ),
    ]
