# Generated by Django 4.2.3 on 2024-12-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_due_at_task_submited_at_task_submited_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remark_note',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='remark_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='remark_status',
            field=models.CharField(blank=True, choices=[('Information', 'Information'), ('Suggestion', 'Suggestion'), ('Requirement', 'Requirement'), ('Unimplement', 'Unimplement')], default='Information', max_length=20, null=True),
        ),
    ]
