# Generated by Django 4.2.3 on 2024-12-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_remark_note_task_remark_seen_task_remark_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remark_status',
            field=models.CharField(blank=True, choices=[('Information', 'Information'), ('Suggestion', 'Suggestion'), ('Requirement', 'Requirement'), ('Unimplement', 'Unimplement')], max_length=20, null=True),
        ),
    ]
